using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Nuke.UI;

[GenerateTypedNameReferences]
public sealed partial class MCNukeWindow : DefaultWindow
{
    public MCNukeWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
