using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Droppod;

[GenerateTypedNameReferences]
public sealed partial class MCDroppodTargetWindow : DefaultWindow
{
    public MCDroppodTargetWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
