- type: entity
  id: MCXenoBase
  abstract: true
  components:
  - type: MobState
    allowedStates:
    - Alive
    - Critical
    - Dead
  - type: NightVision
    overlay: false
    drawFov: false
  - type: MCXenoDamageVisuals
  - type: CombatMode
    canDisarm: false
  - type: MeleeWeapon
    autoAttack: true
    widePrimary: true
    altDisarm: false
    altHeavy: false
  - type: UserInterface
    interfaces:
      # MC
      enum.MCXenoPortalPlacerUI.Key:
        type: MCXenoChoosePortalBui
      enum.MCXenoPlantingWeedsUI.Key:
        type: MCXenoChooseWeedsBui
      # RMC
      enum.XenoEvolutionUIKey.Key:
        type: XenoEvolutionBui
      enum.XenoDevolveUIKey.Key:
        type: XenoDevolveBui
      enum.XenoWatchUIKey.Key:
        type: XenoWatchBui
      enum.XenoChooseStructureUI.Key:
        type: XenoChooseStructureBui
      enum.XenoPheromonesUI.Key:
        type: XenoPheromonesBui
      enum.XenoOrderConstructionUI.Key:
        type: XenoOrderConstructionBui
      enum.XenoFruitChooseUI.Key:
        type: XenoFruitChooseBui
      enum.XenoWordQueenUI.Key:
        type: XenoWordQueenBui
      enum.TacticalMapUserUi.Key:
        type: TacticalMapUserBui
      enum.XenoReserveParasiteChangeUI.Key:
        type: ReserveParasitesBoundUserInterface
      enum.XenoParasiteGhostUI.Key:
        type: XenoParasiteGhostBui
        requireInputValidation: false
      enum.DialogUiKey.Key:
        type: DialogBui

- type: entity
  id: MCXenoPlantingWeeds
  abstract: true
  components:
  - type: MCXenoPlantingWeeds
    selected: MCXenoWeedsNode
    autoSprite:
      sprite: _MC/Interface/Xeno/Actions/general.rsi
      state: repeating
    weeds:
      MCXenoWeedsNode:
        name: Default (75)
        cost: 75
        sprite:
          sprite: _MC/Interface/Xeno/weed_icons.rsi
          state: default
      MCXenoWeedsNodeSticky:
        name: Sticky (150)
        cost: 150
        sprite:
          sprite: _MC/Interface/Xeno/weed_icons.rsi
          state: sticky
      MCXenoWeedsNodeResting:
        name: Resting (225)
        cost: 225
        sprite:
          sprite: _MC/Interface/Xeno/weed_icons.rsi
          state: resting

- type: entity
  id: MCXenoCreateResinJelly
  abstract: true
  components:
  - type: MCXenoCreateResinJelly

- type: entity
  id: MCXenoAcidicSalve
  abstract: true
  components:
  - type: MCXenoAcidicSalve

- type: entity
  id: MCXenoPickupOne
  abstract: true
  components:
  - type: WhitelistPickup
    whitelist:
      components:
      - XenoParasite
      - XenoEgg
      - XenoFruit
  - type: MultiHandedHolder
    items:
    - hands: 2
      whitelist:
        components:
        - XenoEgg

- type: entity
  id: MCXenoRewind
  abstract: true
  components:
  - type: MCXenoRewind

- type: entity
  id: MCXenoBlink
  abstract: true
  components:
  - type: MCXenoBlink

- type: entity
  id: MCXenoPortalPlacer
  abstract: true
  components:
  - type: MCXenoPortalPlacer
    portalFirst:
      id: MCXenoPortalOrange
      icon:
        sprite: _MC/Effects/portals.rsi
        state: orange
    portalSecond:
      id: MCXenoPortalBlue
      icon:
        sprite: _MC/Effects/portals.rsi
        state: blue

- type: entity
  id: MCXenoGrappleToss
  abstract: true
  components:
  - type: MCXenoGrappleToss

- type: entity
  id: MCXenoLayEgg
  abstract: true
  components:
  - type: MCXenoLayEgg

- type: entity
  id: MCXenoCrestToss
  abstract: true
  components:
  - type: MCXenoCrestToss
    damage:
      groups:
        Brute: 36 # distance * 6 (36)
    speed: 10

- type: entity
  id: MCXenoStomp
  abstract: true
  components:
  - type: MCXenoStomp
    throwSpeed: 2
    damage:
      groups:
        Brute: 60

- type: entity
  id: MCXenoCharge
  abstract: true
  components:
  - type: MCXenoCharge
    damage:
      groups:
        Brute: 37
    structureDamage:
      groups:
        Brute: 240

- type: entity
  id: MCXenoHide
  abstract: true
  components:
  - type: XenoHide

- type: entity
  id: MCXenoSpiting
  abstract: true
  components:
  - type: MCXenoSpit
  - type: MCXenoSpitToggle
