using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Chemistry;

[GenerateTypedNameReferences]
public sealed partial class MCChemicalDispenserWindow : DefaultWindow
{
    public MCChemicalDispenserWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
